name: purge_cache
on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  cache:
    runs-on: ubuntu-latest

    steps:
      - name: Purge Cache
        env: 
          ZONE_ID: ${{ secrets.ZONE_ID }}
          GLOBAL_API_KEY: ${{ secrets.GLOBAL_API_KEY }}
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}        
        run: |
          curl -X DELETE "https://api.cloudflare.com/client/v4/zones/${ZONE_ID}/purge_cache" \
          -H "X-Auth-Email: ${EMAIL_ADDRESS}" \
          -H "X-Auth-Key: ${GLOBAL_API_KEY}" \
          -H "Content-Type: application/json" \
          --data '{"purge_everything":true}'

